### ISSUE TITLE
Este teste é uma palhaçada

### ISSUE THREAD

**Issue by netojose** [quartacasa/frontend-challenge#1]
Mas quem foi que elaborou o [Frontend-challenge](https://github.com/quartacasa/frontend-challenge)?

Que tipo de brincadeira é essa?

Uma solução completa com produtos rodando na Web, Mobile, Desktop e ainda a API no backend (o que já é uma piada, se é frontend-challenge, pra que diabos tem que implementar uma API no **backend**)?

Ainda tem o tempo para fazer os Testes e a documentação de componentes?

Como se atrevem a cobrar isso, se não cuidam nem do próprio site? Um formulário que nem validação tem, e que envia os dados usando uma gambiarra.

Sendo bem sinceros, em quantas horas uma pessoa faz isso? Isso com trabalho full time dedicado, é quase um mês. Vocês não tem noção não?

Acham mesmo que vão achar alguém que tope fazer isso? Ninguém com o mínimo de noção vai entrar nisso. Quem é bom, tem o que fazer, está trabalhando, e/ou estudando. E quem tem tempo para fazer isso, não tem competência nos requisitos e/ou não vai conseguir entregar na qualidade que estão esperando.

Vou deixar para vocês, um excelente artigo para leitura: https://medium.com/ui-lab-school/por-que-nao-participo-mais-de-testes-de-avaliacao-tecnica-em-ux-ui-fb39c2327382

**Comment by franciscpd** [comment]
Concordo com você @netojose eu nunca tinha ouvido falar dessa empresa, quem dirá desejar trabalhar lá e com um teste desses kkkk, foi o cúmulo de sem noção.

**Comment by hpandelo** [comment]
Realmente.. o teste é para "one man army" ao invés de frontend. Deve ter um tempo grande pra realizar (1 mês acho muito..). 
Mas parece realmente faltar coerência sobre o tamanho do teste

**Comment by mlozanno** [comment]
Lamentável a atitude de "empresas" como está.
Querem que pessoas desenvolvam a solução completa da sua empresa, de graça, criem um pouco de vergonha na cara.

**Comment by guibranco** [comment]
## Contar tempo a partir do fork ?

Quer dizer que eu posso fazer toda a proposta do teste, e ai eu dou o fork, subo tudo e contabiliza como 1 minuto ?

## Dar fork em teste ? 

Então eu dou fork, criou a solução e por ser um fork o repositório final é public, nisso todo mundo tem acesso ao meu teste, e inclusive pode copiar algumas partes ou todas e como vai ter mais tempo para isso, e tendo conhecimento, vai realizar melhorias que talvez não tenham sido feitas no original para diminuir o tempo ? OU o GH já liberou fork privado ? A última vez que eu vi não tinha ainda...

## Frontend challenge, com mobile, desktop e backend ? 

Quer dizer que o teste é pra frontend, mas o candidato precisa criar uma aplicação em todas as plataformas existentes praticamente e ainda desenvolver o backend ? Aproveita e pede app para Samsung Watch e para smart tv também...

**Comment by netojose** [comment]
@guibranco , eu nem tinha me atentado a esses dois detalhes importantíssimos:
1. Meu teste vai ficar liberado para todos (até vi aqui para ver se já tinha algum fork)
2. Como você disse, já sei dos requisitos, faço tudo, depois faço um fork, só boto minhas coisas já feitas e pronto, fiz tudo em um minuto

kkkkkkk

**Comment by CsnCaio** [comment]
Pra mim, chamar esse teste de **Palhaçada** é ofensa com o palhaço que só quer trazer alegria pra sua plateia.

Eu sou FullStack Sênior, trabalho em uma Software House que só atende clientes gigantes e nunca vi um teste assim.
Querer que o candidato manje de tudo isso é válido, mas existem n maneiras de se fazer isso e essa com certeza é uma das piores.
Já fui líder técnico, já fiz muitas entrevistas e acho que um bom bate papo sobre a tecnologia (perguntas e respostas, ver como o cara desenvolve o pensamento) é uma ótima forma de testar o quão bom o entrevistado é.

Fora isso, não tem mais o que criticar porquê todos os comentários antes do meu já o fizeram.

**Comment by rubenmarcus** [comment]
Fora parte de design UI e UX que os caras falam como se fosse fácil kkkkkkkkk

**Comment by rubenmarcus** [comment]
nas apis eles pedem Basic Authentication mas nao tem a chave Basic aceita

**Comment by deprecat3d** [comment]
Concordo em todos os pontos com os colegas acima. Só acrescento que: se o nome do repositório fosse desafio-full-stack ainda assim seria absurdo. 

É incoerente pedir uma feature de semanas de trabalho para um desafio. Eu realmente fiquei em dúvida se o intuito é avaliar o conhecimento técnico do candidato ou se aproveitar de alguma forma do produto criado por quem submeter esse desafio.

**Comment by guiferpa** [comment]
Fala pessoal, como dito na thread da issue https://github.com/quartacasa/frontend-challenge/issues/2, a ideia do teste não é que todos consiga terminar ele todo e nem mesmo que ele seja feito em minuto :smile: A ideia proposta com o teste é deixa horizontal toda a parte de skill no frontend para saber como cada candidato se comporta com cada skill. Por isso tem coisas referente as 3 frentes de aplicação como Mobile, Web e Nativo. Ninguém da Quarta Casa espera um jedi resolvendo todo o problema em 3 minutos.

**Comment by lfoliveir4** [comment]
> Mas quem foi que elaborou o [Frontend-challenge](https://github.com/quartacasa/frontend-challenge)?
> 
> Que tipo de brincadeira é essa?
> 
> Uma solução completa com produtos rodando na Web, Mobile, Desktop e ainda a API no backend (o que já é uma piada, se é frontend-challenge, pra que diabos tem que implementar uma API no **backend**)?
> 
> Ainda tem o tempo para fazer os Testes e a documentação de componentes?
> 
> Como se atrevem a cobrar isso, se não cuidam nem do próprio site? Um formulário que nem validação tem, e que envia os dados usando uma gambiarra.
> 
> Sendo bem sinceros, em quantas horas uma pessoa faz isso? Isso com trabalho full time dedicado, é quase um mês. Vocês não tem noção não?
> 
> Acham mesmo que vão achar alguém que tope fazer isso? Ninguém com o mínimo de noção vai entrar nisso. Quem é bom, tem o que fazer, está trabalhando, e/ou estudando. E quem tem tempo para fazer isso, não tem competência nos requisitos e/ou não vai conseguir entregar na qualidade que estão esperando.
> 
> Vou deixar para vocês, um excelente artigo para leitura: https://medium.com/ui-lab-school/por-que-nao-participo-mais-de-testes-de-avaliacao-tecnica-em-ux-ui-fb39c2327382

É verdade

![image](https://user-images.githubusercontent.com/32423942/94963599-c8964f00-04ce-11eb-9273-dcf79b13f82a.png)

**Comment by jaburx** [comment]
Que noias, gostei.
