### ISSUE TITLE
Fake Teste

### ISSUE THREAD

**Issue by thauealfredo** [quartacasa/frontend-challenge#2]
Um trabalho de desenvolver uma aplicação real, camuflado como um teste de front-end que engloba API, QA e etc.... Mal do esperto é achar que todo mundo é bobo e só ele é o esperto

**Comment by rubenmarcus** [comment]
e é um teste pra um time inteiro kkkk fazer o Design e tudo mais kkkkkkk

**Comment by netojose** [comment]
Seria mais vantagem eles abrirem várias vagas fake, um para front, um para back, um para UI/UX, etc. mandar cada candidato fazer um pedaço, e no final terem produto deles de graça, do que mandar um único candidato fazer tudo.

**Comment by deprecat3d** [comment]
> Seria mais vantagem eles abrirem várias vagas fake, um para front, um para back, um para UI/UX, etc. mandar cada candidato fazer um pedaço, e no final terem produto deles de graça, do que mandar um único candidato fazer tudo.

Stonks

**Comment by guiferpa** [comment]
Então, pessoal.

A ideia do teste é trabalhar todas as frentes de skill que um frontend possa ter, não queremos nenhum expert no assunto ou se quer alguem que trabalhe de graça em um projeto dado o tramanho.

Ele é complexo e trabalhoso para poder comportar todas as formas de competencia de cada candidato, não espero que o mesmo seja feito por completo mas sim abrir o campo de complexidade para ve como cada candidato aborda o cenário.
